def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'LocationWhenInUse',
  'LocationAlways',
  'Notifications',
  'Camera'
])

target 'safehuntApp' do
  config = use_native_modules!

  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # React Native Vector Icons explicitly defined path
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps/Google', :path => rn_maps_path

  pre_install do |installer|
    static_frameworks = [
      'FirebaseAuthInterop',
      'FirebaseAppCheckInterop',
      'FirebaseCore',
      'FirebaseCoreExtension',
      'GoogleUtilities',
      'RecaptchaInterop',
      'FirebaseInstallations',
      'GoogleDataTransport',
      'nanopb',
      'FirebaseABTesting',
      'FirebaseAuth'
    ]

    installer.pod_targets.each do |pod|
      if static_frameworks.include?(pod.name)
        puts "Configuring #{pod.name} as static framework"
        def pod.build_type
          Pod::BuildType.new(:linkage => :static, :packaging => :framework)
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end